### ISSUE TITLE
[proposal] Extending CLI server with YAML config

### ISSUE THREAD

**Issue by simonas-notcat** [uport-project/veramo#374]
**Is your feature request related to a problem? Please describe.**
At the moment `veramo server` can serve only a limited number of endpoints with one agent configuration.

**Describe the solution you'd like**
Since `veramo server` is basically just an `expressjs` server it can be dynamically extended with additional `Routers` that could be instantiated by the same mechanism we use to construct the agent from YAML config.

This would be useful when writing plugins such as:
 - DID Document serving for `did:web`
 - Well known DID configuration
 - URL shortener for QRCodes
 - Swagger docs
 - Multiple API endpoints with different authorisation (public readonly, private read/write) 
 - Sharing VCs (`/vc/{hash}`)
 - Developer dashboard
 - Revocation list

This configuration could look something like this:

```yml
server:
  baseUrl: http://localhost:3332
  port: 3332
  use:
    - $require: "@veramo/remote-server?#WebDidDocRouter"
      $args:
        - getAgentForRequest:
            $require: "@veramo/remote-server?t=function#getAgentForRequest"
            $args:
              - agent:
                  $ref: /agent

    - $require: "@veramo-community/well-know-did-config?#WellKnownDidConfigRouter"
      $args:
        - getAgentForRequest:
            $require: "@veramo/remote-server?t=function#getAgentForRequest"
            $args:
              - agent:
                  $ref: /agent

    - - "/agent"
      - $require: passport?t=function#authenticate
        $args:
          - bearer
          - session: false
      - $require: "@veramo/remote-server?#AgentRouter"
        $args:
          - getAgentForRequest:
              $require: "@veramo/remote-server?t=function#getAgentForRequest"
              $args:
                - agent:
                    $ref: /agent
            exposedMethods:
              - keyManagerGetKeyManagementSystems
              - keyManagerCreate
              - keyManagerGet
              - keyManagerDelete

    - - "/public"
      - $require: "@veramo/remote-server?#AgentRouter"
        $args:
          - getAgentForRequest:
              $require: "@veramo/remote-server?t=function#getAgentForRequest"
              $args:
                - agent:
                    $ref: /publicAgent
            exposedMethods:
              - dataStoreORMGetVerifiableCredentials
              - dataStoreORMGetVerifiableCredentialsCount

    - - "/open-api.json"
      - $require: "@veramo/remote-server#ApiSchemaRouter"
        $args:
          - basePath: /agent
            securityScheme: bearer
            apiName: Agent
            apiVersion: "1.0.0"
            exposedMethods:
              - keyManagerGetKeyManagementSystems
              - keyManagerCreate
              - keyManagerGet
              - keyManagerDelete
            getAgentForRequest:
              $require: "@veramo/remote-server?t=function#getAgentForRequest"
              $args:
                - agent:
                    $ref: /agent

    - - "/api-docs"
      - $require: "@veramo-community/swagger?#SwaggerRouter"
        $args:
          - getAgentForRequest:
              $require: "@veramo/remote-server?t=function#getAgentForRequest"
              $args:
                - agent:
                    $ref: "/agent"

agent:
  $require: "@veramo/core#Agent"
  $args:
    - plugins:
        - $require: "@veramo/key-manager#KeyManager"
        # - ...

publicAgent:
  $require: "@veramo/core#Agent"
  $args:
    - plugins:
        - $require: "@veramo/data-store#DataStoreORM"
          $args:
            - $ref: /dbConnection/public

dbConnection:
  public:
    $require: typeorm?t=function#createConnection
    $args:
      - type: sqlite
        database:
          $ref: /constants/databaseFile
        synchronize: true
        logging: false
        entities:
          $require: "@veramo/data-store?t=object#Entities"
  private:
    $require: typeorm?t=function#createConnection
    $args:
      - type: sqlite
        database:
          $ref: /constants/databaseFile
        synchronize: true
        logging: false
        entities:
          $require: "@veramo/data-store?t=object#Entities"
```
